language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - ymll@live.hk
      - anshumanmohan@live.com
      - jerome_derrick@hotmail.com

before_script: gradle clean

script: gradle check -i

after_script: gradle fatJar cobertura coveralls
