language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - ymll@live.hk
      - anshumanmohan@live.com
      - jerome_derrick@hotmail.com

script: gradle clean check cobertura coveralls -i
